In [2]:
import pandas as pd

In [3]:
df = pd.read_json("TelecomX_Data.json")

df_extracted = pd.json_normalize(df.to_dict(orient='records'))

df_extracted.replace({
    'No internet service': 'No',
    'No phone service': 'No'
}, inplace=True)

df_extracted.columns = df_extracted.columns.str.strip()

if 'account.TotalCharges' in df_extracted.columns:
    df_extracted['account.TotalCharges'] = pd.to_numeric(df_extracted['account.TotalCharges'], errors='coerce')

In [4]:

categorical_columns = [
    'Churn',
    'customer.gender',
    'customer.Partner',
    'customer.Dependents',
    'phone.PhoneService',
    'phone.MultipleLines',
    'internet.InternetService',
    'internet.OnlineSecurity',
    'internet.OnlineBackup',
    'internet.DeviceProtection',
    'internet.TechSupport',
    'internet.StreamingTV',
    'internet.StreamingMovies',
    'account.Contract',
    'account.PaperlessBilling',
    'account.PaymentMethod'
]

df_encoded = pd.get_dummies(df_extracted, columns=categorical_columns, drop_first=False)


df_encoded.head()

,customerID,customer.SeniorCitizen,customer.tenure,account.Charges.Monthly,account.Charges.Total,Churn_,Churn_No,Churn_Yes,customer.gender_Female,customer.gender_Male,...,internet.StreamingMovies_Yes,account.Contract_Month-to-month,account.Contract_One year,account.Contract_Two year,account.PaperlessBilling_No,account.PaperlessBilling_Yes,account.PaymentMethod_Bank transfer (automatic),account.PaymentMethod_Credit card (automatic),account.PaymentMethod_Electronic check,account.PaymentMethod_Mailed check
0,0002-ORFBO,0,9,65.6,593.3,False,True,False,True,False,...,False,False,True,False,False,True,False,False,False,True
1,0003-MKNFE,0,9,59.9,542.4,False,True,False,False,True,...,True,True,False,False,True,False,False,False,False,True
2,0004-TLHLJ,0,4,73.9,280.85,False,False,True,False,True,...,False,True,False,False,False,True,False,False,True,False
3,0011-IGKFF,1,13,98.0,1237.85,False,False,True,False,True,...,True,True,False,False,False,True,False,False,True,False
4,0013-EXCHZ,1,3,83.9,267.4,False,False,True,True,False,...,False,True,False,False,False,True,False,False,False,True

In [6]:

redundant_columns = [
    'Churn_',  # coluna inÃºtil criada pelo encoder
    'Churn_No',  # redundante com Churn_Yes
]

original_cat_columns = [
    'customer.gender',
    'customer.Partner',
    'customer.Dependents',
    'phone.PhoneService',
    'phone.MultipleLines',
    'internet.InternetService',
    'internet.OnlineSecurity',
    'internet.OnlineBackup',
    'internet.DeviceProtection',
    'internet.TechSupport',
    'internet.StreamingTV',
    'internet.StreamingMovies',
    'account.Contract',
    'account.PaperlessBilling',
    'account.PaymentMethod'
]

cols_to_drop = [col for col in redundant_columns + original_cat_columns if col in df_encoded.columns]
df_cleaned = df_encoded.drop(columns=cols_to_drop)

In [7]:
df_cleaned.to_pickle("TelecomX_tratado.pickle")